#!/bin/sh
# Arvolo installer — downloads the prebuilt `arvolo` (and `arvolo-relay`) binaries
# for your platform from the latest GitHub Release and installs them.
#
#   curl -fsSL https://raw.githubusercontent.com/lords82/arvolo/main/install.sh | sh
#
# Overrides (environment):
#   ARVOLO_VERSION       tag to install, e.g. v0.1.0 (default: latest published)
#   ARVOLO_INSTALL_DIR   install directory (default: /usr/local/bin, else ~/.local/bin)
#
# POSIX sh, no bashisms. Prebuilt binaries currently cover Linux x86_64, Linux
# aarch64, and macOS (one archive for both Apple Silicon and Intel); other
# platforms fall back to `cargo install`.
set -eu

REPO="lords82/arvolo"
BINARIES="arvolo arvolo-relay"

info() { printf '%s\n' "$*" >&2; }
err() { printf 'error: %s\n' "$*" >&2; exit 1; }

need() { command -v "$1" >/dev/null 2>&1 || err "missing required tool: $1"; }

cargo_fallback() {
  info ""
  info "No prebuilt binary for this platform ($1). Install from source instead:"
  info "    cargo install --git https://github.com/$REPO arvolo-cli"
  info "    cargo install --git https://github.com/$REPO arvolo-relay"
  exit 1
}

# --- detect platform -------------------------------------------------------
os="$(uname -s)"
arch="$(uname -m)"
# Each platform names the archives it can use, best first. macOS lists two: one
# archive now holds both architectures, and "macos-arm64" stays behind it so this
# script can still install a release cut before that was true — someone pinning
# ARVOLO_VERSION to an older tag should not be told their Mac is unsupported.
case "$os" in
  Linux)
    case "$arch" in
      x86_64 | amd64) labels="linux-x86_64" ;;
      aarch64 | arm64) labels="linux-aarch64" ;;
      *) cargo_fallback "$os/$arch" ;;
    esac ;;
  Darwin)
    case "$arch" in
      arm64 | aarch64) labels="macos-universal macos-arm64" ;;
      x86_64 | amd64) labels="macos-universal" ;;
      *) cargo_fallback "$os/$arch" ;;
    esac ;;
  *) cargo_fallback "$os/$arch" ;;
esac

# --- pick a download tool --------------------------------------------------
if command -v curl >/dev/null 2>&1; then
  dl() { curl -fsSL "$1" -o "$2"; }
  fetch() { curl -fsSL "$1"; }
elif command -v wget >/dev/null 2>&1; then
  dl() { wget -qO "$2" "$1"; }
  fetch() { wget -qO- "$1"; }
else
  err "need curl or wget"
fi
need tar

# --- resolve version -------------------------------------------------------
tag="${ARVOLO_VERSION:-}"
if [ -z "$tag" ]; then
  info "Resolving the latest release…"
  tag="$(fetch "https://api.github.com/repos/$REPO/releases/latest" \
    | grep '"tag_name"' | head -n1 | cut -d'"' -f4)"
  [ -n "$tag" ] || err "could not determine the latest release (is one published, not just draft?). Set ARVOLO_VERSION=vX.Y.Z"
fi

base="https://github.com/$REPO/releases/download/$tag"

# --- download + verify + extract ------------------------------------------
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT INT TERM

# Take the first candidate this release actually has. Asking the release rather
# than assuming means one script serves tags from either side of the change.
asset=""
for l in $labels; do
  candidate="arvolo-${tag}-${l}.tar.gz"
  if dl "$base/$candidate" "$tmp/$candidate" 2>/dev/null; then
    label="$l"; asset="$candidate"; break
  fi
done
# Nothing published for this platform at this tag — which for an Intel Mac means
# a tag older than the universal build. Point at the source route rather than
# reporting a bare download failure, since that route does work.
[ -n "$asset" ] || cargo_fallback "$os/$arch at $tag"
info "Installing arvolo $tag ($label)…"

# Best-effort SHA256 verification against the release's SHA256SUMS.
sumtool=""
if command -v sha256sum >/dev/null 2>&1; then sumtool="sha256sum"
elif command -v shasum >/dev/null 2>&1; then sumtool="shasum -a 256"; fi
if [ -n "$sumtool" ] && dl "$base/SHA256SUMS" "$tmp/SHA256SUMS" 2>/dev/null; then
  want="$(grep " $asset\$" "$tmp/SHA256SUMS" | awk '{print $1}' | head -n1)"
  if [ -n "$want" ]; then
    got="$($sumtool "$tmp/$asset" | awk '{print $1}')"
    [ "$want" = "$got" ] || err "checksum mismatch for $asset (expected $want, got $got)"
    info "Checksum OK."
  fi
else
  info "Skipping checksum verification (no SHA256SUMS or sha256 tool)."
fi

tar -xzf "$tmp/$asset" -C "$tmp"

# --- choose install dir ----------------------------------------------------
dir="${ARVOLO_INSTALL_DIR:-/usr/local/bin}"
sudo=""
if [ ! -d "$dir" ] || [ ! -w "$dir" ]; then
  if [ "${ARVOLO_INSTALL_DIR:-}" = "" ] && [ -w "/usr/local" ] 2>/dev/null; then
    :
  elif [ "${ARVOLO_INSTALL_DIR:-}" = "" ] && command -v sudo >/dev/null 2>&1 && [ -d "$dir" ]; then
    sudo="sudo"
  else
    dir="$HOME/.local/bin"
    mkdir -p "$dir"
  fi
fi

for b in $BINARIES; do
  [ -f "$tmp/$b" ] || continue
  $sudo install -m 0755 "$tmp/$b" "$dir/$b"
  info "Installed $dir/$b"
done

# --- shell completions -----------------------------------------------------
# The completion script is generated by the binary we just installed, so there is
# nothing to download: `arvolo completions <shell>` prints a small shim that calls
# back into arvolo on every <TAB>. That indirection is what lets it offer your
# contact names and live transfer ids, not just the command names.
#
# We only drop a file where the shell *already* auto-loads one — an existing
# completions directory means the user opted into this mechanism. Everywhere else
# we print the command and let them decide: an installer piped from curl has no
# business editing shell startup files.
completion_hint=""
case "$(basename "${SHELL:-}")" in
  bash)
    cdir="${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion/completions"
    if [ -d "$cdir" ] && "$dir/arvolo" completions bash > "$cdir/arvolo" 2>/dev/null; then
      info "Installed $cdir/arvolo (restart your shell for <TAB> completion)"
    else
      completion_hint="arvolo completions bash > $cdir/arvolo"
    fi ;;
  fish)
    cdir="${XDG_CONFIG_HOME:-$HOME/.config}/fish/completions"
    if [ -d "$cdir" ] && "$dir/arvolo" completions fish > "$cdir/arvolo.fish" 2>/dev/null; then
      info "Installed $cdir/arvolo.fish (restart your shell for <TAB> completion)"
    else
      completion_hint="arvolo completions fish > $cdir/arvolo.fish"
    fi ;;
  zsh)
    # zsh needs the directory on `fpath`, which we can't arrange from here.
    completion_hint="arvolo completions zsh > ~/.zfunc/_arvolo   # and put ~/.zfunc on your fpath"
    ;;
  *) completion_hint="arvolo completions <bash|zsh|fish|elvish|powershell>" ;;
esac

# --- PATH hint -------------------------------------------------------------
case ":$PATH:" in
  *":$dir:"*) ;;
  *) info ""
     info "Note: $dir is not on your PATH. Add it, e.g.:"
     info "    export PATH=\"$dir:\$PATH\"" ;;
esac

if [ -n "$completion_hint" ]; then
  info ""
  info "For <TAB> completion (commands, your contacts, live transfer ids):"
  info "    $completion_hint"
fi

info ""
info "Done. Try: arvolo --help"
